Using numpy and other functions from the package

In [1]:
kanto = [73 , 67, 43]
johto = [91, 88, 64]


writing a function to find the crop_yield to calculate the yield of apples(or any other crop) given the climate data and the respective weights.

In [2]:
w1,w2,w3 = 0.3,0.4,0.5

In [3]:
weights = [w1, w2, w3]

In [4]:
weights

[0.3, 0.4, 0.5]

use the inbuilt zip function to do linear multiplication on lists

In [5]:
for item in zip(kanto , weights):
    print(item)

(73, 0.3)
(67, 0.4)
(43, 0.5)


using zip function to multiply the items and add them as a linear function

In [6]:
def crop_yield(region,weights):
    result = 0
    for x, w in zip(region, weights):
        result += x*w
    return result

In [7]:
crop_yield(kanto, weights)

70.2

Dot product in two vectors 

In [8]:
import numpy as np


Numpy arrays can be created using the np.array function

In [9]:
kanto = np.array([73, 67, 43])

In [10]:
kanto

array([73, 67, 43])

In [11]:
weights = np.array([w1,w2,w3])

In [12]:
weights

array([0.3, 0.4, 0.5])

In [13]:
type (weights)

numpy.ndarray

In [14]:
type (kanto)

numpy.ndarray

Indexing is like arrays

we can do dot product using numpy function np.dot

In [15]:
np.dot(kanto,weights)

70.2

In [16]:
kanto

array([73, 67, 43])

In [17]:
weights

array([0.3, 0.4, 0.5])

In [18]:
kanto * weights

array([21.9, 26.8, 21.5])

In [19]:
(kanto * weights).sum()

70.2

using the .sum() function sums all the elements on numpy array

Multi dimensional numpy arrays

In [20]:
climate_data = np.array([[73,65,32],
                       [65,32,25],
                       [56,23,24]])

In [21]:
climate_data

array([[73, 65, 32],
       [65, 32, 25],
       [56, 23, 24]])

In [22]:
climate_data.shape

(3, 3)

In [23]:
weights.shape

(3,)

In [24]:
# 3D array
arr3 = np.array([[[11,12,13],[25,36,36]]])

In [25]:
arr3.shape

(1, 2, 3)

In [26]:
weights.dtype

dtype('float64')

In [27]:
climate_data.dtype

dtype('int32')

In [28]:
np.matmul(climate_data, weights)

array([63.9, 44.8, 38. ])

matmul fuction does the matrix multiplication

@ also does the matrix multiplication

In [29]:
climate_data @ weights

array([63.9, 44.8, 38. ])

In [30]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x29243724400>)

In [31]:
climate_data = np.genfromtxt('climate.txt',delimiter =',', skip_header=1)

np.genfromtxt retrieves data from csv as numpy arrays

In [32]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [33]:
climate_data.shape

(10000, 3)

In [34]:
weights = np.array([0.3,0.2,0.50])

In [35]:
yields = climate_data @ weights

In [36]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [37]:
yields.shape

(10000,)

now we want to add yields column on climate.txt file. To do that we use np.concatenate function frim numpy package

In [38]:
 climate_results = np.concatenate((climate_data, yields.reshape(10000,1)), axis = 1)

In [39]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [40]:
help (np.reshape)

Help on function reshape in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
        c

to save the file from numpy package use np.savetxt

In [45]:
np.savetxt('climate_results.txt',
           climate_results,
          fmt = '%.2f',
          header = 'temperature,rainfall,humidity,yields',
          comments ='')

 array indexing and slicing

In [46]:
arr3 = np.array([
    [[11, 12, 13, 14], 
     [13, 14, 15, 19]], 
    
    [[15, 16, 17, 21], 
     [63, 92, 36, 18]], 
    
    [[98, 32, 81, 23],      
     [17, 18, 19.5, 43]]])

In [47]:
arr3.shape

(3, 2, 4)

In [48]:
# Single element
arr3[1,1,2]

36.0

In [49]:
arr3[1,1]

array([63., 92., 36., 18.])

In [50]:
arr3[1,1,3]

18.0

Above mentioned steps are the ways to obtain the certain element on the numpy array

In [52]:
arr3[1:]

array([[[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [53]:
arr3[1:, 0:1]

array([[[15., 16., 17., 21.]],

       [[98., 32., 81., 23.]]])

In [54]:
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [56]:
np.arange(10, 90, 3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58,
       61, 64, 67, 70, 73, 76, 79, 82, 85, 88])

In [58]:
np.arange(10, 90, 3).reshape(3,3,3)

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34]],

       [[37, 40, 43],
        [46, 49, 52],
        [55, 58, 61]],

       [[64, 67, 70],
        [73, 76, 79],
        [82, 85, 88]]])

In [60]:
np.arange(10,90,3).shape

(27,)

In [63]:
# Equally spaced numbers
np.linspace(3,27,16)

array([ 3. ,  4.6,  6.2,  7.8,  9.4, 11. , 12.6, 14.2, 15.8, 17.4, 19. ,
       20.6, 22.2, 23.8, 25.4, 27. ])